### ISSUE TITLE
cassandra python driver 2.1.4 crash on pypy-2.5 not pypy3-2.4

### ISSUE THREAD

**Issue by morsdatum** [datastax/python-driver#261]
While running in pypy-2.5 it give out segmentation fault with a core dump,the program run fine in pypy3-2.4(both pypy/pypy3 install the same python driver)

**Comment by avalanche123** [comment]
Please use Python driver jira issue tracker, you can find the link in the README

**Comment by aholmberg** [comment]
Thanks for bringing this up. We usually don't have Issues open on GitHub (this is a temporary state for trying to gather contributor agreements). The JIRA mentioned above: https://datastax-oss.atlassian.net/projects/PYTHON/summary

If you file a JIRA, please try to provide detailed information about the crash, and scripts to reproduce.
