### ISSUE TITLE
How do I deal with nan and infinity

### ISSUE THREAD

**Issue by dmlayton** [datastax/python-driver#264]
I am using numpy and cqlengine. My model has Float columns, but when I do:
`MyModel.create(my_float=numpy.nan)` 
I recieve:
`InvalidRequest: code=2200 [Invalid query] message="unable to coerce 'nan' to a double"`
similarly if I do:
``MyModel.create(my_float=numpy.inf)` ` or ``MyModel.create(my_float=float('inf'))` `
I get:
`SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:150 no viable alternative at input ')' (... VALUES (ba9424e0-0e6b-49d9-a18a-8fd340216ed5, 1427971488046, [inf]))">`
These values are supported for CQL as literals NAN and INFINITY.

**Comment by aholmberg** [comment]
It looks like Python represents those values differently than expected in CQL. I've opened an issue in JIRA: https://datastax-oss.atlassian.net/browse/PYTHON-282

Please use JIRA for issues. We normally don't have github issues open -- this is a temporary state for gathering Contributor License Agreements.
