### ISSUE TITLE
Get Distinct Values Using CQLEngine (Object Mapper) 

### ISSUE THREAD

**Issue by prafulbagai** [datastax/python-driver#267]
How to get the distinct values in CQLEngine?

`class UserByGender(Model):`
    `    gender = Text(primary_key=True)`
    `date = DateTime(primary_key=True,default=datetime.now())`
   ` user_id = UUID(index=True)`

For the above model, the similar query format in CQL is:-

`SELECT distinct gender FROM user_by_gender ; `

How do I write the similar query in CQLEngine? 

Please let me know if there is anything possible of his sort? Or if theres any practical hack available?

**Comment by aholmberg** [comment]
That feature is not yet implemented in cqlengine. We have a JIRA open [here](https://datastax-oss.atlassian.net/browse/PYTHON-266). Pull requests are welcome.

Please direct questions to the [mailing list](https://groups.google.com/a/lists.datastax.com/forum/#!forum/python-driver-user), and new issues to [JIRA](https://datastax-oss.atlassian.net/browse/PYTHON)
