### ISSUE TITLE
TwistedConnection uses connectTCP, but should probably use Endpoints instead

### ISSUE THREAD

**Issue by glyph** [datastax/python-driver#271]
The [high-level “endpoints” API](http://twistedmatrix.com/documents/current/core/howto/endpoints.html) within Twisted is far more flexible and robust than hard-coding the low-level `connectTCP`.

For a very basic example, [HostnameEndpoint](https://twistedmatrix.com/documents/current/api/twisted.internet.endpoints.HostnameEndpoint.html) would let you transparently support IPv6 addresses and use the "happy eyeballs" algorithm to establish connections more quickly.

At a higher level, you could use [`clientFromString`](https://twistedmatrix.com/documents/current/api/twisted.internet.endpoints.html#clientFromString) to allow users to configure arbitrary endpoints from Twisted's endpoint plugin system, including TLS endpoints with client certificates, Tor connections, SSH tunnels, subprocesses and so on.

**Comment by aholmberg** [comment]
Thanks for providing this input. I've captured it in our JIRA as a possible improvement. https://datastax-oss.atlassian.net/browse/PYTHON-290
